networks:
  project:

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      # - ./docker/data/mysql:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - project

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    command: php artisan serve --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - project

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - project
